### ISSUE TITLE
Image doesn't change when variation selected for Woocommerce 3.0.0 RC1 or RC2

### ISSUE THREAD

**Issue by seanlane** [thriveweb/wooswipe#13]
FYI, looks like there might be a breaking change with Woocommerce 3.0.0 coming out. When different variations have their own images, the main image should change to that image when the variation is selected. I tested this in versions 3.0.0 RC1 & RC2 (found [here](https://github.com/woocommerce/woocommerce/releases)) and the image does not change. Tested with Woocommerce version 2.6.14, and it does work.

**Comment by thriveweb** [comment]
All fixed :)
