### ISSUE TITLE
Clicking an image to lightbox it results in two lightboxes

### ISSUE THREAD

**Issue by HammyHavoc** [thriveweb/wooswipe#18]
Any insight into this?

You can see it happening here: [https://www.hammyhavoc.com/product/cracks-beneath-our-feet/](https://www.hammyhavoc.com/product/cracks-beneath-our-feet/)

**Comment by deanoakley** [comment]
I think this was a theme conflict bot a bug. Looks like you have moved to another plugin. Sorry I couldn't look into it in time!
