### ISSUE TITLE
Requested: Add captions to slideshow.

### ISSUE THREAD

**Issue by deanoakley** [thriveweb/wooswipe#19]
Looks like this could pull from the image details.

**Comment by zkg** [comment]
+1 This feature would be very useful indeed.

**Comment by burzumumbra** [comment]
I'm working an implementation of this.

**Comment by burzumumbra** [comment]
@zkg this resolve your issue?

**Comment by zkg** [comment]
Nope, that works only for the first image of the gallery. I know what's wrong...

**Comment by burzumumbra** [comment]
@zkg really just the first one? I'll test it, all my products have the same Alt Text.

**Comment by zkg** [comment]
@burzumumbra yep, the .find() method only returned the first element. No problem though, I fixed it.

**Comment by burzumumbra** [comment]
@zkg the power of collaboration

**Comment by zkg** [comment]
@burzumumbra yeah, open source is like - magic pixie dust - or something! :smiley:

**Comment by deanoakley** [comment]
Thanks for your work on this @burzumumbra !
